In [42]:
import string
import numpy as np
import csv
import pandas as pd

In [43]:
def substrings_in_string(big_string, substrings):
    for substring in substrings:
        if substring in big_string:
            return substring
    #print(substring)
    return np.nan

In [44]:
def get_data_from_file(file_location):
    file_content=[]

    with open(file_location) as csvfile:
        file = csv.reader(csvfile)
        for eachline in file:
            file_content.append(eachline)
    
    df=pd.DataFrame(file_content)
    new_header = df.iloc[0]
    df = df[1:]
    df.columns = new_header
    return df

In [45]:
 #Data Engineering

def process_train_data(df):
    
    ##Cherbourg 1
    ##Queenstown 2
    ##Southampton 3

    df['Embarked'] = df['Embarked'].replace(to_replace = "C",value = 1)
    df['Embarked'] = df['Embarked'].replace(to_replace = "Q",value = 2)
    df['Embarked'] = df['Embarked'].replace(to_replace = "S",value = 3)
    
    
    df['Fare'] = pd.to_numeric(df['Fare'])
    df['Age'] = pd.to_numeric(df['Age'])
    
    df['FamilySize'] = pd.to_numeric(df['SibSp'])+pd.to_numeric(df['Parch'])
    
    cabin_list = ['A', 'B', 'C', 'D', 'E', 'F', 'T', 'G', 'Unknown']
    df['Deck']=df['Cabin'].map(lambda x: substrings_in_string(x, cabin_list))
    
    df = df.replace(to_replace = np.NaN, value=0)
    df = df.replace(to_replace = '',value = 0)
    df = df.replace(to_replace = "male", value = 1)
    df = df.replace(to_replace = "female",value = 2)
    
    new_df = df[['PassengerId','Pclass','Sex','Age','Embarked','Fare','FamilySize','Survived']]
    
    return new_df

In [46]:
 #Data Engineering

def process_test_data(df):
    
    ##Cherbourg 1
    ##Queenstown 2
    ##Southampton 3

    df['Embarked'] = df['Embarked'].replace(to_replace = "C",value = 1)
    df['Embarked'] = df['Embarked'].replace(to_replace = "Q",value = 2)
    df['Embarked'] = df['Embarked'].replace(to_replace = "S",value = 3)
    
    
    df['Fare'] = pd.to_numeric(df['Fare'])
    df['Age'] = pd.to_numeric(df['Age'])
    
    df['FamilySize'] = pd.to_numeric(df['SibSp'])+pd.to_numeric(df['Parch'])
    
    cabin_list = ['A', 'B', 'C', 'D', 'E', 'F', 'T', 'G', 'Unknown']
    df['Deck']=df['Cabin'].map(lambda x: substrings_in_string(x, cabin_list))
    
    df = df.replace(to_replace = np.NaN, value=0)
    df = df.replace(to_replace = '',value = 0)
    df = df.replace(to_replace = "male", value = 1)
    df = df.replace(to_replace = "female",value = 2)
    
    new_df = df[['PassengerId','Pclass','Sex','Age','Embarked','Fare','FamilySize']]
    
    return new_df

In [47]:
def write_output(prediction,file_name):
    with open(file_name,'w', newline='') as my_csv:
        csvWriter = csv.writer(my_csv,delimiter=',')
        csvWriter.writerows(prediction)

In [48]:
new_df = get_data_from_file('./train.csv')
new_df = process_train_data(new_df)

In [49]:
new_df

0   PassengerId Pclass  Sex   Age  Embarked      Fare  FamilySize Survived
1             1      3    1  22.0         3    7.2500           1        0
2             2      1    2  38.0         1   71.2833           1        1
3             3      3    2  26.0         3    7.9250           0        1
4             4      1    2  35.0         3   53.1000           1        1
5             5      3    1  35.0         3    8.0500           0        0
6             6      3    1   0.0         2    8.4583           0        0
7             7      1    1  54.0         3   51.8625           0        0
8             8      3    1   2.0         3   21.0750           4        0
9             9      3    2  27.0         3   11.1333           2        1
10           10      2    2  14.0         1   30.0708           1        1
11           11      3    2   4.0         3   16.7000           2        1
12           12      1    2  58.0         3   26.5500           0        1
13           13      3    1  20.0         3    8.0500           0        0
14           14      3    1  39.0         3   31.2750           6        0
15           15      3    2  14.0         3    7.8542           0        0
16           16      2    2  55.0         3   16.0000           0        1
17           17      3    1   2.0         2   29.1250           5        0
18           18      2    1   0.0         3   13.0000           0        1
19           19      3    2  31.0         3   18.0000           1        0
20           20      3    2   0.0         1    7.2250           0        1
21           21      2    1  35.0         3   26.0000           0        0
22           22      2    1  34.0         3   13.0000           0        1
23           23      3    2  15.0         2    8.0292           0        1
24           24      1    1  28.0         3   35.5000           0        1
25           25      3    2   8.0         3   21.0750           4        0
26           26      3    2  38.0         3   31.3875           6        1
27           27      3    1   0.0         1    7.2250           0        0
28           28      1    1  19.0         3  263.0000           5        0
29           29      3    2   0.0         2    7.8792           0        1
30           30      3    1   0.0         3    7.8958           0        0
..          ...    ...  ...   ...       ...       ...         ...      ...
862         862      2    1  21.0         3   11.5000           1        0
863         863      1    2  48.0         3   25.9292           0        1
864         864      3    2   0.0         3   69.5500          10        0
865         865      2    1  24.0         3   13.0000           0        0
866         866      2    2  42.0         3   13.0000           0        1
867         867      2    2  27.0         1   13.8583           1        1
868         868      1    1  31.0         3   50.4958           0        0
869         869      3    1   0.0         3    9.5000           0        0
870         870      3    1   4.0         3   11.1333           2        1
871         871      3    1  26.0         3    7.8958           0        0
872         872      1    2  47.0         3   52.5542           2        1
873         873      1    1  33.0         3    5.0000           0        0
874         874      3    1  47.0         3    9.0000           0        0
875         875      2    2  28.0         1   24.0000           1        1
876         876      3    2  15.0         1    7.2250           0        1
877         877      3    1  20.0         3    9.8458           0        0
878         878      3    1  19.0         3    7.8958           0        0
879         879      3    1   0.0         3    7.8958           0        0
880         880      1    2  56.0         1   83.1583           1        1
881         881      2    2  25.0         3   26.0000           1        1
882         882      3    1  33.0         3    7.8958           0        0
883         883      3    2  22.0         3   10.5167           0        0
884         884      2    1  28.0         3   10.5000           0        0
885         885      3    1  25.0         3    7.0500           0        0
886         886      3    2  39.0         2   29.1250           5        0
887         887      2    1  27.0         3   13.0000           0        0
888         888      1    2  19.0         3   30.0000           0        1
889         889      3    2   0.0         3   23.4500           3        0
890         890      1    1  26.0         1   30.0000           0        1
891         891      3    1  32.0         2    7.7500           0        0

[891 rows x 8 columns]

In [50]:
data = new_df[['PassengerId','Pclass','Sex','Age','Embarked','Fare','FamilySize']]

In [51]:
prediction = new_df[['Survived']]

In [52]:
from sklearn import svm

clf = svm.SVC(kernel='linear',C=0.01)

In [53]:
clf.fit(data,prediction)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:547: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(C=0.01, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [54]:
from sklearn.ensemble import RandomForestClassifier

clf_rf = RandomForestClassifier(max_depth=7, random_state=2)
clf_rf.fit(data,prediction)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=7, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=2, verbose=0, warm_start=False)

In [55]:

def train_data_test_SVC(data):
    data_train = data[0:int(0.8*len(data))]
    prediction_train = prediction[0:int(0.8*len(data))]
    data_test = data[int(0.8*len(data)):]
    prediction_test = prediction[int(0.8*len(data)):]
    
    from sklearn import svm

    clf = svm.SVC(kernel='linear',C=0.01)
    clf.fit(data_train,prediction_train)
    
    pred_sur = clf.predict(data_test)
    
    from sklearn.metrics import accuracy_score

    print(accuracy_score(pred_sur,prediction_test))
    

train_data_test_SVC(data)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:547: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.837988826816

In [56]:
def train_data_test_RF(data):
    data_train = data[0:int(0.8*len(data))]
    prediction_train = prediction[0:int(0.8*len(data))]
    data_test = data[int(0.8*len(data)):]
    prediction_test = prediction[int(0.8*len(data)):]
    
    from sklearn.ensemble import RandomForestClassifier

    clf_rf = RandomForestClassifier(max_depth=7, random_state=2)
    clf_rf.fit(data_train,prediction_train)
    
    pred_sur = clf_rf.predict(data_test)
    
    from sklearn.metrics import accuracy_score

    print(accuracy_score(pred_sur,prediction_test))
    

train_data_test_RF(data)

0.860335195531

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.

In [57]:
original_test_data = get_data_from_file('./test.csv')
original_test_data = process_test_data(original_test_data)

In [58]:
##Linear SVM
prediction_test_data_svc = clf.predict(original_test_data)

In [59]:
##Linear SVM

id_num=0
prediction=[]
titles=[]
titles.append("PassengerId")
titles.append("Survived")
prediction.append(titles)
ids = original_test_data['PassengerId']

for x in prediction_test_data_svc:
    id_num+=1
    id_prediction=[]
    id_prediction.append(int(ids[id_num]))
    id_prediction.append(int(x))
    prediction.append(id_prediction)
    
write_output(prediction,"output_svm_linear.csv")

In [60]:
prediction_test_data_rf = clf_rf.predict(original_test_data)

In [61]:
##Random Forest

id_num=0
prediction=[]
titles=[]
titles.append("PassengerId")
titles.append("Survived")
prediction.append(titles)
ids = original_test_data['PassengerId']

for x in prediction_test_data_rf:
    id_num+=1
    id_prediction=[]
    id_prediction.append(int(ids[id_num]))
    id_prediction.append(int(x))
    prediction.append(id_prediction)
    
write_output(prediction,"output_random_forest.csv")